apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openkruise-cloneset-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/maheshkasabe/kruise-argo/'
    path: example/openkruise_workloads/cloneset/
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true      # to create the namaspace if not exsists
    automated:
      prune: true
      selfHeal: true